/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public interface liquidfunConstants {
  int B2_ASSERT_ENABLED = liquidfunJNI.B2_ASSERT_ENABLED_get();
  double _pi = liquidfunJNI._pi_get();
  int LIQUIDFUN_EXTERNAL_LANGUAGE_API = liquidfunJNI.LIQUIDFUN_EXTERNAL_LANGUAGE_API_get();
  int _maxManifoldPoints = liquidfunJNI._maxManifoldPoints_get();
  int _maxPolygonVertices = liquidfunJNI._maxPolygonVertices_get();
  double _aabbExtension = liquidfunJNI._aabbExtension_get();
  double _aabbMultiplier = liquidfunJNI._aabbMultiplier_get();
  double _linearSlop = liquidfunJNI._linearSlop_get();
  double _angularSlop = liquidfunJNI._angularSlop_get();
  double _polygonRadius = liquidfunJNI._polygonRadius_get();
  int _maxSubSteps = liquidfunJNI._maxSubSteps_get();
  int _maxTOIContacts = liquidfunJNI._maxTOIContacts_get();
  double _velocityThreshold = liquidfunJNI._velocityThreshold_get();
  double _maxLinearCorrection = liquidfunJNI._maxLinearCorrection_get();
  double _maxAngularCorrection = liquidfunJNI._maxAngularCorrection_get();
  double _maxTranslation = liquidfunJNI._maxTranslation_get();
  double _maxTranslationSquared = liquidfunJNI._maxTranslationSquared_get();
  double _maxRotation = liquidfunJNI._maxRotation_get();
  double _maxRotationSquared = liquidfunJNI._maxRotationSquared_get();
  double _baumgarte = liquidfunJNI._baumgarte_get();
  double _toiBaugarte = liquidfunJNI._toiBaugarte_get();
  int _invalidParticleIndex = liquidfunJNI._invalidParticleIndex_get();
  int _maxParticleIndex = liquidfunJNI._maxParticleIndex_get();
  double _particleStride = liquidfunJNI._particleStride_get();
  double _minParticleWeight = liquidfunJNI._minParticleWeight_get();
  double _maxParticlePressure = liquidfunJNI._maxParticlePressure_get();
  double _maxParticleForce = liquidfunJNI._maxParticleForce_get();
  int _maxTriadDistance = liquidfunJNI._maxTriadDistance_get();
  int _maxTriadDistanceSquared = liquidfunJNI._maxTriadDistanceSquared_get();
  int _minParticleSystemBufferCapacity = liquidfunJNI._minParticleSystemBufferCapacity_get();
  double _barrierCollisionTime = liquidfunJNI._barrierCollisionTime_get();
  double _timeToSleep = liquidfunJNI._timeToSleep_get();
  double _linearSleepTolerance = liquidfunJNI._linearSleepTolerance_get();
  double _angularSleepTolerance = liquidfunJNI._angularSleepTolerance_get();
}
